# Generated by Django 5.0.4 on 2024-04-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_code_registro_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Code_registro',
            new_name='code_registro',
        ),
    ]
